/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedList;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test public void testTheInstanceOfLinkedlistClass() {
    LinkedList linkedinTestWithNoArguments = new LinkedList();
    LinkedList linkedinTestWithArguments = new LinkedList(1);

    assertEquals("Test type of linkedinTest Object", true,linkedinTestWithNoArguments.getClass() == LinkedList.class);
    assertEquals("Test if linkedList object is instanceof LinkedList class", true,linkedinTestWithNoArguments instanceof LinkedList);
    assertEquals("check making instance of class with input value", true,linkedinTestWithArguments instanceof LinkedList);
  }

  @Test public void testTheInsertMethod() {
    LinkedList linkedinTestWithNoArguments = new LinkedList();
    assertEquals("Test The initial value of the head of linked list without insert value", null,linkedinTestWithNoArguments.head);

    linkedinTestWithNoArguments.insert(1);
    assertEquals("Test The initial value of the head of linked list after insert value", 1,(int) linkedinTestWithNoArguments.head.value);

    linkedinTestWithNoArguments.insert(2);
    assertEquals("Test the value of the head after add the 2nd value", 2,(int) linkedinTestWithNoArguments.head.value);

    assertEquals("Test the string of the linked list after adding new nodes", "{ 2 } -> { 1 } -> NULL",linkedinTestWithNoArguments.toString());

    assertEquals("Is the linked list include the first inserted item", true,linkedinTestWithNoArguments.includes(1));
  }

  @Test public void testIncludeMethod() {
    LinkedList linkedinTestWithNoArguments = new LinkedList();
    linkedinTestWithNoArguments.insert(1);
    linkedinTestWithNoArguments.insert(2);

    assertEquals("Is the linked list include the first inserted item", true,linkedinTestWithNoArguments.includes(1));

    assertEquals("Is the linked list include the 2nd inserted item", true,linkedinTestWithNoArguments.includes(2));

    assertEquals("Is the linked list include Method with not inserted value", false,linkedinTestWithNoArguments.includes(3));
  }

  @Test public void testTheHead() {
    LinkedList linkedinTestWithNoArguments = new LinkedList();
    assertEquals("Test The initial value of the head", null,linkedinTestWithNoArguments.head);

    assertEquals("Test the class of the head after insert", true,linkedinTestWithNoArguments instanceof LinkedList);

    linkedinTestWithNoArguments.insert(1);
    assertEquals("Test the class of the head after insert", true,linkedinTestWithNoArguments instanceof LinkedList);
  }

  //    assertEquals("Test the string of the linked list", "NULL",linkedinTestWithNoArguments.toString());
  @Test public void testToString() {
    LinkedList linkedinTestWithNoArguments = new LinkedList();
    assertEquals("Test the string of the linked without adding values", "NULL",linkedinTestWithNoArguments.toString());

    linkedinTestWithNoArguments.insert(1);
    linkedinTestWithNoArguments.insert(2);

    assertEquals("Test the string of the linked list after adding new nodes", "{ 2 } -> { 1 } -> NULL",linkedinTestWithNoArguments.toString());
  }
}
