/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedList;

public class App {
    public static void main(String[] args) {
      LinkedList linkedList = new LinkedList();
      System.out.println(linkedList.includes(2));
      System.out.println(linkedList.toString());
      System.out.println(linkedList.insert(1));
      System.out.println(linkedList.insert(2));
      System.out.println(linkedList.toString());
      System.out.println(linkedList.includes(2));
      System.out.println(linkedList.includes(1));

    }
}
